version: '3'
services:
  # Postgres
  postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=500'
    ports:
      # Accessible from the host at port :35432
      - '45432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: livestream  
    # Make sure log colors show up correctly
    tty: true
  