import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const clickHandler = async () => {
    return null;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col gap-5 items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-white text-xl">Login page with tPRC</h1>

        <form action="" className="flex flex-col w-full px-5 gap-5">
          <input type="text" placeholder="email" className="rounded p-2" />
          <button onClick={clickHandler} className="text-white p-2 border">Email me this magic link</button>
        </form>
      </main>
    </>
  );
};

export default Home;
